[deps]
Turing = "fce5fe82-541a-59a6-adf8-730c64b5f9a0"
StableRNGs = "860ef19b-820b-49d6-a774-d7a799459cd3"
Coinfer = "2494631e-bceb-4539-8821-5341beee86e1"

[coinfer]
entrance_file = "model.jl"

[sources.Coinfer]
rev = "main"
url = "https://github.com/vectorly-ai/coinfer-sdk"
subdir = "client/Coinfer.jl"
